version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/addup-backend

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: scripts/health-check.sh
      timeout: 10
      runas: ubuntu
