version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/addup-backend

permissions:
  - object: /
    pattern: '**'
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/health-check.sh
      timeout: 10
      runas: root
