version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - echo Entered the install phase...
      - npm i
  build:
    commands:
      - echo Entered the build phase...
      - npm run lint
      - npm test
artifacts:
  files:
    - 'dist/**/*'
  name: addup-backend-build
